version: '3'

services:
  zk1:
    image: zookeeper:3.6
    hostname: zk1
    container_name: ch-zk1
    ports:
      - "12181:2181"
    networks:
      ch-cluster:
        ipv4_address: 172.20.1.2
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
  zk2:
    image: zookeeper:3.6
    hostname: zk2
    container_name: ch-zk2
    ports:
      - "22181:2181"
    networks:
      ch-cluster:
        ipv4_address: 172.20.1.3
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
  zk3:
    image: zookeeper:3.6
    hostname: zk3
    container_name: ch-zk3
    ports:
      - "32181:2181"
    networks:
      ch-cluster:
        ipv4_address: 172.20.1.4
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181

  ch01:
    image: yandex/clickhouse-server:${CLICKHOUSE_VERSION:-20.11}
    ports:
      - "8124:8123"
    hostname: ch01
    container_name: ch-server-ch01
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      ch-cluster:
        ipv4_address: 172.20.1.5
    extra_hosts:
      - "zk1:172.20.1.2"
      - "zk2:172.20.1.3"
      - "zk3:172.20.1.4"
      - "ch02:172.20.1.6"
      - "ch03:172.20.1.7"
      - "ch04:172.20.1.8"
    volumes:
      - ./metrika_ch01.xml:/etc/metrika.xml
    depends_on:
      - "zk1"
      - "zk2"
      - "zk3"

  ch02:
    image: yandex/clickhouse-server:${CLICKHOUSE_VERSION:-20.11}
    ports:
      - "8125:8123"
    hostname: ch02
    container_name: ch-server-ch02
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      ch-cluster:
        ipv4_address: 172.20.1.6
    extra_hosts:
      - "zk1:172.20.1.2"
      - "zk2:172.20.1.3"
      - "zk3:172.20.1.4"
      - "ch01:172.20.1.5"
      - "ch03:172.20.1.7"
      - "ch04:172.20.1.8"
    volumes:
      - ./metrika_ch02.xml:/etc/metrika.xml
    depends_on:
      - "zk1"
      - "zk2"
      - "zk3"

  ch03:
    image: yandex/clickhouse-server:${CLICKHOUSE_VERSION:-20.11}
    ports:
      - "8126:8123"
    hostname: ch03
    container_name: ch-server-ch03
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      ch-cluster:
        ipv4_address: 172.20.1.7
    extra_hosts:
      - "zk1:172.20.1.2"
      - "zk2:172.20.1.3"
      - "zk3:172.20.1.4"
      - "ch01:172.20.1.5"
      - "ch02:172.20.1.6"
      - "ch04:172.20.1.8"
    volumes:
      - ./metrika_ch03.xml:/etc/metrika.xml
    depends_on:
      - "zk1"
      - "zk2"
      - "zk3"

  ch04:
    image: yandex/clickhouse-server:${CLICKHOUSE_VERSION:-20.11}
    ports:
      - "8127:8123"
    hostname: ch04
    container_name: ch-server-ch04
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      ch-cluster:
        ipv4_address: 172.20.1.8
    extra_hosts:
      - "zk1:172.20.1.2"
      - "zk2:172.20.1.3"
      - "zk3:172.20.1.4"
      - "ch01:172.20.1.5"
      - "ch02:172.20.1.6"
      - "ch03:172.20.1.7"
    volumes:
      - ./metrika_ch04.xml:/etc/metrika.xml
    depends_on:
      - "zk1"
      - "zk2"
      - "zk3"

networks:
  ch-cluster:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/16
